market: BOS-12
rules:
  - action: allow
    src: 10.20.0.0/16
    dst: 10.20.0.0/16
    proto: any
  - action: allow
    host: 10.20.4.17
    ports: [22, 161, 443]
    device: core-rtr-bos-12
  - action: allow
    host: 10.20.4.30
    ports: [22, 161, 443]
    device: core-rtr-bos-12-01
  - action: allow
    host: 10.20.4.37
    ports: [22, 161, 443]
    device: agg-sw-bos-12-02
  - action: allow
    host: 10.20.4.44
    ports: [22, 161, 443]
    device: cell-rtr-bos-12-03
  - action: allow
    host: 10.20.4.51
    ports: [22, 161, 443]
    device: cpe-gw-bos-12-04
  - action: allow
    host: 10.20.9.100
    ports: [22, 161, 443]
    device: peer-edge-01
  - action: allow
    host: 10.20.250.12
    ports: [22, 161, 443]
    device: agg-sw-growth-01
