market: SEA-06
rules:
  - action: allow
    src: 10.20.0.0/16
    dst: 10.20.0.0/16
    proto: any
  - action: allow
    host: 10.20.17.30
    ports: [22, 161, 443]
    device: core-rtr-sea-06-01
  - action: allow
    host: 10.20.17.37
    ports: [22, 161, 443]
    device: agg-sw-sea-06-02
  - action: allow
    host: 10.20.17.44
    ports: [22, 161, 443]
    device: cell-rtr-sea-06-03
  - action: allow
    host: 10.20.17.51
    ports: [22, 161, 443]
    device: cpe-gw-sea-06-04
